### ISSUE TITLE
Update Heroku Ruby to 2.1.x or higher

### ISSUE THREAD

**Issue by bayendor** [bayendor/big_brother#24]
Default Ruby version unless specified is 2.0.0, which will not accept the hash structure output by command line client.  We should specify a version 2.1.x or higher, preferably, 2.2.1 if possible.

**Comment by bayendor** [comment]
I believe this can be fixed  by setting `CUSTOM_RUBY_VERSION` in the `.env` file and using `ruby ENV['CUSTOM_RUBY_VERSION'] || '2.0.0'` in our `Gemfile`.

**Comment by dalexj** [comment]
I like this CUSTOM_RUBY_VERSION because I won't have to install a new version of ruby cuz I'm lazy.
